(import (pcsc shell)
	(getopt)
	(srfi :39))

(define (main args)
  (define (usage args)
    (print (car args) ": -f $file [-v]")
    (exit #f))
  (with-args args ((file (#\f "file") #t (usage args))
		   (verbose (#\v "verbose") #f #f))
    (parameterize ((*verbose* verbose))
      (pcsc-load file))))